import { expect, test } from "@playwright/test";
import { prepare, start, halt, papers, interact, close, probe } from "./breakdownTestDriver";
for (const response of ["sealed", "ask"]) test(`breakdown ${response}: spatial work, private papers and canonical restore`, async ({ page }) => {
  test.setTimeout(210000); await prepare(page, response === "ask" ? "intervene" : "whistle"); const before = await probe(page, "save");
  await start(page); const moving = await probe(page, "save"); const x = moving.player.x;
  await page.keyboard.down("a"); try { await expect.poll(async () => (await probe(page, "inspect")).player.x).toBeLessThan(x - 8); }
  finally { await page.keyboard.up("a"); } await halt(page);
  const stopped = await probe(page, "save"), riverX = stopped.riverX;
  await expect.poll(async () => (await probe(page, "inspect")).riverX).not.toBe(riverX);
  expect((await probe(page, "inspect")).bankX).toBe(stopped.bankX);
  await expect.poll(async () => (await probe(page, "inspect")).sources.find((s: { id: string }) => s.id === "journey-kurtz-breakdown:engine:channel")?.volume,
    { timeout: 15000 }).toBe(0);
  await probe(page, "go", "forge"); await expect(page.getByTestId("talk-prompt")).not.toContainText("Avivar");
  await papers(page); await expect(page.getByTestId("dialogue-text")).toContainText(response === "ask" ? "Ya leí su informe" : "cordón de zapato");
  const choice = await probe(page, "save"); await page.keyboard.press(response === "sealed" ? "1" : "2"); await close(page);
  const custody = await probe(page, "save"); expect(custody.state.papersResponse).toBe(response); expect(custody.papersVisible).toBe(false);
  await interact(page, "patient", "cómo sigue"); await expect(page.getByTestId("dialogue-text")).toContainText(response === "ask" ? "fotografía" : "cordón sigue atado"); await close(page);
  await probe(page, "go", "helm"); await expect(page.getByTestId("talk-prompt")).not.toContainText("Probar la máquina");
  await interact(page, "engine", "Examinar"); await close(page); await interact(page, "forge", "Avivar"); await close(page);
  await expect.poll(async () => (await probe(page, "inspect")).state.repairProgress).toBeGreaterThan(.15);
  await probe(page, "go", "far"); await probe(page, "settleFrame"); const work = await probe(page, "save");
  expect(work.state.repairProgress).toBeLessThan(1); await probe(page, "settleFrame");
  expect((await probe(page, "inspect")).state.repairProgress).toBe(work.state.repairProgress);
  await probe(page, "go", "forge"); await expect.poll(async () => (await probe(page, "inspect")).state.repairProgress, { timeout: 30000 }).toBe(1);
  await interact(page, "engine", "montar"); await close(page); expect((await probe(page, "inspect")).rodVisible).toBe(false);
  await interact(page, "helm", "Probar la máquina"); await page.keyboard.press("e");
  await expect(page.getByTestId("dialogue-text")).toContainText(response === "ask" ? "rostro de alguien" : "cordón sigue intacto"); await close(page);
  const completed = await probe(page, "save"); expect(completed.state.phase).toBe("underway"); expect(completed.state.finalSeen).toBe(true);
  const restoredMoving = await probe(page, "restore", moving.data);
  expect(restoredMoving.state.distance).toBe(moving.state.distance); expect(restoredMoving.player).toEqual(moving.player);
  expect(restoredMoving.state.phase).toBe("downstream");
  await expect.poll(async () => (await probe(page, "inspect")).state.distance).toBeGreaterThan(moving.state.distance);
  const restoredWork = await probe(page, "restore", work.data); expect(restoredWork.player).toEqual(work.player);
  expect(restoredWork.state).toEqual(work.state); expect(restoredWork.bankX).toBe(work.bankX);
  await expect.poll(async () => (await probe(page, "inspect")).patientFrame).toEqual({ x: 768, y: 512, width: 768, height: 512 });
  expect((await probe(page, "inspect")).patientSize).toEqual({ width: 315, height: 210 });
  await probe(page, "restore", completed.data); await probe(page, "restore", completed.data);
  expect((await probe(page, "inspect")).labels).toEqual([]);
  expect((await probe(page, "inspect")).entities.every((e: { count: number }) => e.count === 1)).toBe(true);
  expect((await probe(page, "inspect")).sources.every((s: { count: number }) => s.count <= 1)).toBe(true);
  await probe(page, "restore", choice.data); await expect(page.getByTestId("dialogue-choice")).toHaveCount(2);
  expect((await probe(page, "inspect")).state.papersResponse).toBeUndefined();
  await probe(page, "restore", custody.data); await probe(page, "go", "patient");
  await expect(page.getByTestId("talk-prompt")).toContainText("cómo sigue"); expect((await probe(page, "inspect")).state.papersResponse).toBe(response);
  await probe(page, "restore", stopped.data); await probe(page, "settleFrame");
  expect((await probe(page, "inspect")).labels).toEqual([]); expect((await probe(page, "inspect")).state.breakdownSeen).toBe(true);
  await probe(page, "restore", before.data); expect((await probe(page, "inspect")).state.phase).toBe("inactive");
  await probe(page, "go", "entry"); await expect(page.getByTestId("talk-prompt")).toContainText("Continuar río abajo");
  await probe(page, "restart"); expect((await probe(page, "inspect")).state.phase).toBe("inactive");
  expect((await probe(page, "inspect")).sources.every((s: { count: number }) => s.count === 0)).toBe(true);
  expect(await page.evaluate(() => window.pixiVN.errors)).toEqual([]);
});
test("breakdown entry requires the closed departure and actual helm proximity", async ({ page }) => {
  test.setTimeout(150000); const { prepare: prior } = await import("./departureTestDriver"); await prior(page);
  await probe(page, "go", "entry"); await expect(page.getByTestId("talk-prompt")).not.toContainText("Continuar río abajo");
  expect((await probe(page, "inspect")).state.phase).toBe("inactive");
  await probe(page, "completeDeparture"); await probe(page, "go", "far"); await page.keyboard.press("e");
  expect((await probe(page, "inspect")).state.phase).toBe("inactive"); await start(page); await halt(page);
  await probe(page, "go", "far"); await page.keyboard.press("e"); expect((await probe(page, "inspect")).state.papersResponse).toBeUndefined();
  expect((await probe(page, "inspect")).state.engineExamined).toBe(false);
  expect(await page.evaluate(() => window.pixiVN.errors)).toEqual([]);
});
