import { expect, test } from "@playwright/test";
import { reveal, start, darken, track, confront, close, escort, probe, examine } from "./nightEscapeTestDriver";
for (const choice of [1, 2]) test(`night escape ${choice}: search, confrontation, supported return and canonical saves`, async ({ page }) => {
  test.setTimeout(240000); await reveal(page, choice);
  const before = await probe(page, "save"); await start(page);
  expect((await probe(page, "inspect")).player).toEqual({ x: 420, y: 745 });
  expect((await probe(page, "inspect")).state.phase).toBe("dusk");
  await expect.poll(async () => (await probe(page, "inspect")).night).toBeGreaterThan(.05);
  const dusk = await probe(page, "save"); expect(dusk.night).toBeLessThan(.99);
  await darken(page); expect((await probe(page, "inspect")).resting).toBe(false);
  const restoredDusk = await probe(page, "restore", dusk.data);
  expect(restoredDusk.state.phase).toBe("dusk"); expect(restoredDusk.night).toBe(dusk.night); await darken(page);
  await track(page); const tracking = await probe(page, "save");
  expect(tracking.state.traces).toEqual(["grass", "prints", "branches"]); expect(tracking.kurtz.visible).toBe(true);
  await confront(page); const atChoice = await probe(page, "save");
  await page.keyboard.press(String(choice)); const value = choice === 1 ? "reason" : "challenge";
  await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "mañana podrá" : "Esta noche vuelve");
  const selected = await probe(page, "save"); expect(selected.state.choice).toBe(value);
  expect(selected.state.pose).toBe(choice === 1 ? "bracing" : "dominant");
  await probe(page, "restore", atChoice.data); await expect(page.getByTestId("dialogue-choice")).toHaveCount(2);
  expect((await probe(page, "inspect")).state.choice).toBeUndefined();
  await probe(page, "restore", selected.data); expect((await probe(page, "inspect")).state.choice).toBe(value);
  await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "mañana podrá" : "Esta noche vuelve");
  const x = (await probe(page, "inspect")).player.x; await page.keyboard.down("d");
  try { await expect.poll(async () => (await probe(page, "inspect")).player.x).toBeGreaterThan(x + 10); } finally { await page.keyboard.up("d"); }
  await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "todavía hubiera tiempo" : "mi voz");
  await close(page); expect((await probe(page, "inspect")).state.phase).toBe("return");
  await probe(page, "go", "beside"); await probe(page, "settleFrame");
  const supported = (await probe(page, "inspect")).state.escort.x;
  await page.keyboard.down("d");
  try { await expect.poll(async () => (await probe(page, "inspect")).state.escort.x).toBeGreaterThan(supported + 3); }
  finally { await page.keyboard.up("d"); }
  await probe(page, "go", "exit"); await expect(page.getByTestId("talk-prompt")).toContainText("detenido");
  const abandoned = (await probe(page, "inspect")).state.escort;
  await probe(page, "settleFrame"); expect((await probe(page, "inspect")).state.escort).toEqual(abandoned);
  const supporting = await probe(page, "save");
  await escort(page); await expect(page.getByTestId("dialogue-text")).toContainText("Bajamos juntos");
  const returned = await probe(page, "save"); await page.keyboard.press("e");
  await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "Qué prudente" : "mi obediencia");
  await close(page); expect((await probe(page, "inspect")).state.returnedSeen).toBe(true);
  const supportedRestore = await probe(page, "restore", supporting.data);
  expect(supportedRestore.state.phase).toBe("return"); expect(supportedRestore.state.escort).toEqual(supporting.state.escort);
  await probe(page, "restore", returned.data); await expect(page.getByTestId("dialogue-text")).toContainText("Bajamos juntos");
  expect((await probe(page, "inspect")).state.choice).toBe(value); await close(page);
  const final = await probe(page, "inspect"); expect(final.previousChoice).toBe(choice === 1 ? "understand" : "brutality");
  expect(final.firstResponse).toBe(choice === 1 ? "listen" : "challenge");
  expect(final.entities.every((entity: { count: number }) => entity.count === 1)).toBe(true);
  expect(final.sources.every((source: { count: number }) => source.count <= 1)).toBe(true);
  await probe(page, "restore", tracking.data); expect((await probe(page, "inspect")).state.choice).toBeUndefined();
  expect((await probe(page, "inspect")).player).toEqual(tracking.player);
  await probe(page, "restore", before.data); expect((await probe(page, "inspect")).state.phase).toBe("inactive");
  expect(await page.evaluate(() => window.pixiVN.errors)).toEqual([]);
});
test("night entry is gated, partial tracking restores and a restart removes the entire episode", async ({ page }) => {
  test.setTimeout(180000);
  const { enter } = await import("./revelationsTestDriver"); await enter(page);
  await probe(page, "go", "vigil"); await expect(page.getByTestId("talk-prompt")).not.toContainText("guardia");
  await page.reload(); await reveal(page); await start(page); await darken(page);
  await examine(page, "bed", "vacío"); await close(page);
  await examine(page, "grass", "hierba"); const partial = await probe(page, "save"); await close(page);
  await examine(page, "prints", "barro"); await close(page);
  await probe(page, "restore", partial.data); await expect(page.getByTestId("dialogue-text")).toContainText("arrastrado");
  expect((await probe(page, "inspect")).state.traces).toEqual(["grass"]);
  expect((await probe(page, "inspect")).player).toEqual(partial.player); await close(page);
  expect((await probe(page, "inspect")).entities.every((entity: { count: number }) => entity.count === 1)).toBe(true);
  await probe(page, "restart"); await expect(page.getByTestId("talk-prompt")).toBeVisible();
  expect((await probe(page, "inspect")).state.phase).toBe("inactive");
  expect((await probe(page, "inspect")).sources.every((source: { count: number }) => source.count === 0)).toBe(true);
  expect(await page.evaluate(() => window.pixiVN.errors)).toEqual([]);
});
