import { expect, test } from "@playwright/test";
import { enter, probe, investigate, closeDialogue } from "./revelationsTestDriver";
for (const choice of [1, 2]) test(`station revelations ${choice}: different orders, two-clue gate, interpretation and canonical restores`, async ({ page }) => {
  test.setTimeout(180000); await enter(page, choice);
  const position = (await probe(page, "inspect")).player;
  expect(position).toEqual({ x: 1225, y: 800 }); expect((await probe(page, "inspect")).response).toBe(choice === 1 ? "listen" : "challenge");
  const before = await probe(page, "save");
  const order = choice === 1 ? ["ivory", "palisade", "report", "influence"] : ["report", "influence", "ivory", "palisade"];
  await investigate(page, order[0]); expect((await probe(page, "inspect")).ready).toBe(false);
  const one = await probe(page, "save"); await investigate(page, order[1]);
  expect((await probe(page, "inspect")).ready).toBe(true);
  await probe(page, "restore", one.data); expect((await probe(page, "inspect")).discoveries).toEqual([order[0]]);
  expect((await probe(page, "inspect")).player).toEqual(one.player); expect((await probe(page, "inspect")).ready).toBe(false);
  await investigate(page, order[1]); const two = await probe(page, "save");
  await probe(page, "go", "russian"); await expect(page.getByTestId("talk-prompt")).toContainText("ruso");
  await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "rebeldes" : "sus papeles");
  const active = await probe(page, "save"); const mood = (await probe(page, "inspect")).mood;
  await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "lo dejó hablar" : "Antes se atrevió");
  await probe(page, "restore", active.data); await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "rebeldes" : "sus papeles");
  expect((await probe(page, "inspect")).mood).toBe(mood); expect((await probe(page, "inspect")).labels).toHaveLength(1);
  await page.keyboard.press("e"); await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-choice")).toHaveCount(2);
  const atChoice = await probe(page, "save"); await page.keyboard.press(String(choice));
  await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "Comprenderlo no vuelve" : "brutalidad");
  const chosen = await probe(page, "save"); const value = choice === 1 ? "understand" : "brutality";
  expect((await probe(page, "inspect")).interpretation).toBe(value);
  await probe(page, "restore", atChoice.data); await expect(page.getByTestId("dialogue-choice")).toHaveCount(2);
  expect((await probe(page, "inspect")).interpretation).toBeUndefined();
  await probe(page, "restore", chosen.data); expect((await probe(page, "inspect")).interpretation).toBe(value);
  await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "Comprenderlo no vuelve" : "brutalidad");
  expect((await probe(page, "inspect")).labels).toHaveLength(2);
  await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "separado entenderlo" : "lo defendía");
  await closeDialogue(page); expect((await probe(page, "inspect")).complete).toBe(true);
  for (const id of order.slice(2)) await investigate(page, id);
  expect((await probe(page, "inspect")).discoveries).toEqual(order); expect((await probe(page, "inspect")).flags).toEqual([true, true, true, true]);
  await probe(page, "go", "russian"); await page.keyboard.press("e");
  await expect(page.getByTestId("dialogue-text")).toContainText("rebeldes");
  await page.keyboard.press("e"); await page.keyboard.press("e");
  await expect(page.getByTestId("dialogue-text")).toContainText("Cada cosa"); expect(await page.getByTestId("dialogue-choice").count()).toBe(0);
  await closeDialogue(page); await probe(page, "go", "kurtz"); await page.keyboard.press("e");
  await expect(page.getByTestId("dialogue-text")).toContainText(choice === 1 ? "Quiere comprenderme" : "un nombre que la explique");
  const x = (await probe(page, "inspect")).player.x; await page.keyboard.down("a");
  try { await expect.poll(async () => (await probe(page, "inspect")).player.x).toBeLessThan(x - 15); }
  finally { await page.keyboard.up("a"); }
  await closeDialogue(page); expect((await probe(page, "inspect")).sources.every((s: { count: number }) => s.count <= 1)).toBe(true);
  const restored = await probe(page, "restore", two.data); expect(restored.discoveries).toEqual(order.slice(0, 2));
  expect(restored.interpretation).toBeUndefined(); expect(restored.pressure).toBe(two.pressure);
  await probe(page, "restore", before.data); expect((await probe(page, "inspect")).discoveries).toEqual([]);
  expect((await probe(page, "inspect")).complete).toBe(false); expect((await probe(page, "inspect")).player).toEqual(position);
  expect(await page.evaluate(() => window.pixiVN.errors)).toEqual([]);
});
test("palisade is an ambiguous object until recognition; partial document and revelation restore without replay", async ({ page }) => {
  test.setTimeout(120000); await enter(page); await probe(page, "go", "palisade");
  await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-text")).toContainText("De lejos");
  expect((await probe(page, "inspect")).discoveries).toEqual([]); const distant = await probe(page, "save");
  await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-text")).toContainText("cabezas humanas");
  const revealed = await probe(page, "save"); await probe(page, "restore", distant.data);
  await expect(page.getByTestId("dialogue-text")).toContainText("De lejos"); expect((await probe(page, "inspect")).discoveries).toEqual([]);
  await probe(page, "restore", revealed.data); await expect(page.getByTestId("dialogue-text")).toContainText("cabezas humanas");
  expect((await probe(page, "inspect")).discoveries).toEqual(["palisade"]); await closeDialogue(page);
  await probe(page, "go", "report"); await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-text")).toContainText("hacer el bien");
  await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-text")).toContainText("Hago una pausa");
  expect((await probe(page, "inspect")).discoveries).toEqual(["palisade"]);
  const partial = await probe(page, "save"); await page.keyboard.press("e"); await expect(page.getByTestId("dialogue-text")).toContainText("Exterminad");
  await probe(page, "restore", partial.data); await expect(page.getByTestId("dialogue-text")).toContainText("Hago una pausa");
  await page.keyboard.press("e"); await closeDialogue(page); expect((await probe(page, "inspect")).discoveries).toEqual(["palisade", "report"]);
  await investigate(page, "palisade"); expect((await probe(page, "inspect")).discoveries).toEqual(["palisade", "report"]);
  expect(await page.evaluate(() => window.pixiVN.errors)).toEqual([]);
});
