export const metamorphosisText = {
  gregorName: "Gregor Samsa",
  windowPrompt: "E · Mirar por la ventana",
  doorPrompt: "E · Escuchar junto a la puerta",
  exitPrompt: "E · Abrir la puerta y salir",
  gretePrompt: "E · Hablar con Grete",
  returnPrompt: "E · Volver a la habitación",
  picturePrompt: "E · Mirar el cuadro del pasillo",
  hallwayPicture: "En el cuadro del pasillo, una casa tranquila parecía pertenecer a otra familia.",
  window: [
    "Tras el cristal, la calle seguía su mañana como si nada hubiera ocurrido.",
    "Gregor apoyó una pata en el marco. La lluvia le devolvió una silueta que no reconocía.",
  ],
  doorBeforeWindow: "Al otro lado de la puerta, la voz de su hermana se apagó al oírlo acercarse.",
  doorAfterWindow: "La lluvia aún golpeaba el cristal cuando Grete habló tras la puerta.",
  familyApproach: "Gregor oyó pasos apresurados detrás de la puerta. Su madre volvió a pronunciar su nombre en voz baja.",
  familyQuestion: "Gregor, madre pregunta si puedes responder. ¿Te encuentras bien?",
  familyChoices: ["Intentar responderles.", "Permanecer en silencio."],
  familyAnswered: "Estoy bien, madre... Gregor se detuvo: su voz le resultó irreconocible.",
  familySilent: "Gregor abrió la boca, pero decidió no decir nada.",
  familyAfterAnswer: "Te hemos oído, pero madre no ha entendido lo que dijiste.",
  familyAfterSilence: "Sigue llamándote, Gregor. Cree que aún estás dormido.",
  familyReturnAnswer: "Madre sigue inquieta por lo que oyó en tu voz.",
  familyReturnSilence: "Madre ha vuelto a preguntar por qué no contestas.",
  clerkArrival: "El timbre sonó en la casa. Grete abrió a un representante de la oficina: Gregor no se había presentado al trabajo.",
  clerkGreteAfterAnswer: "Madre oyó tu voz hace un momento. Ahora ha llegado alguien de la oficina, Gregor.",
  clerkGreteAfterSilence: "Como no respondiste, madre está aún más inquieta. Hay alguien de la oficina aquí.",
  clerkQuestion: "Señor Samsa, ¿por qué no acudió al trabajo esta mañana? Abra la puerta y explíquese.",
  clerkChoices: ["Intentar justificar mi ausencia.", "Guardar silencio."],
  clerkExplain: "No pude ir... Me encuentro mal, pero saldré en cuanto pueda.",
  clerkSilence: "No. No puedo responderle todavía.",
  clerkAfterExplain: "Su voz suena extraña. Abra la puerta, señor Samsa; necesitamos verlo.",
  clerkAfterSilence: "Señor Samsa, su silencio solo aumenta nuestra preocupación. Abra la puerta.",
  greteQuestion: "Gregor, ¿quieres que me quede aquí un momento?",
  choices: ["Quédate. Háblame desde ahí.", "Déjame solo por ahora."],
  gregorStay: "Quédate, Grete. Necesito oír tu voz.",
  gregorLeave: "Déjame solo, Grete. Todavía no estoy preparado.",
  greteAfterStay: "Me quedaré junto a la puerta. No tienes que responder.",
  greteAfterLeave: "De acuerdo. Estaré al final del pasillo si me necesitas.",
  greteReturnStay: "Sigo aquí, Gregor. Te escucho.",
  greteReturnLeave: "He vuelto solo para saber si estás bien.",
} as const;
